---
# blurbs
blurbs:
  - cite: 'Erin Rollman & Brian Colonna'
    org: 'Buntport Theatre'
    org_url: 'http://buntport.com/'
    body: "A really, really good reading time! Eric has gathered all of the beauteous, ugly, and necessary parts together in one place. The characters, ideas, story are exposed, raw, alive — merging masculine and feminine into some kind of mystical marriage. Graciously, Eric leaves us the pleasure of assembly without rules."

  - cite: 'Chris Eppstein'
    org: 'Core Developer of Compass & Sass'
    org_url: 'http://compass-style.org'
    body: "Rarely do you get to experience such intimate thoughts. It's like being dropped into someone's head, Quantum Leap style, for a transformative time in their life. Super sexy. I won't deny, it turned me&nbsp;on."

  - cite: 'Natalie Weizenbaum'
    org: 'Lead Designer/Developer of Sass'
    org_url: 'http://sass-lang.com'
    body: "This feels more realistic than any other novel could hope to be: every moment is just one in a sea of other moments, no more or less important, although no less interesting for that. The result is an impressionist array of feelings and emotions and understandings of oneself and others."


# defaults
title: Riding SideSaddle*
author: eric
author_full: Eric M Suzanne
location: home
copyright: 2015
description: An open-source novel on notecards — created by Eric M Suzanne, and published by SpringGun Press.
longdesc: "Riding SideSaddle* is an open-source novel on notecards — a fragmented memory of our time together, and these bodies we inhabit — created by Eric Suzanne, with contributions from Jacob Liechty, Sondra Eby, Aaron Liechty, and others — published by SpringGun Press."
keywords: novel, elit, experimental, art, collage, open-source, creative commons, oddbook


# Site Config
active_modules: [blog, typogrify, author, wrap]
canonical_url: http://www.ridingsidesaddle.net/
output_folder: ../../sidesaddle-pages
template_path: ../templates
modules:
  blog:
    index_url: /blog/
