---
# blurbs
blurbs:
  - cite: 'Erin Rollman & Brian Colona'
    org: 'Buntport Theatre'
    org_url: 'http://buntport.com/'
    body: "A really, really good reading time! Eric has gathered all the beauteous, ugly, and necessary parts together in one place. Graciously, he leaves us the pleasure of assembly without&nbsp;rules."

  - cite: 'Chris Eppstein'
    org: 'Sass & Compass'
    org_url: 'http://sass-lang.com/'
    body: "Rarely do you get to experience such intimate thoughts. It's like being dropped into someone's head, Quantum Leap style, for a transformative time in their life. Super sexy. I won't deny, it turned me&nbsp;on."


# defaults
title: Riding SideSaddle*
author: eric
author_full: Eric M Suzanne
location: home
copyright: 2015
description: An open-source novel on note cards â€” created by Eric M Suzanne, and published by SpringGun Press.
keywords: novel, elit, experimental, art, collage, open-source, creative commons, oddbook


# Site Config
active_modules: [blog, typogrify, author, wrap]
canonical_url: http://ridingsidesaddle.net/
output_folder: ../../sidesaddle-pages
template_path: ../templates
modules:
  blog:
    index_url: /blog/
